import{S as g,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const f="48154537-527b84123da1832c7b7680c8e",m="https://pixabay.com/api/";function h(o){const n=`${m}?key=${f}&q=${o}&page=1&per_page=15&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(t=>{if(!t.ok)throw new Error("Failed to fetch images");return t.json()}).then(t=>t.hits).catch(t=>{throw console.error(t),new Error("Something went wrong!")})}function p(o){const n=document.querySelector(".gallery");if(o.length===0){iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const t=o.map(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:l,comments:u,downloads:d})=>`
        <a href="${e}" class="gallery-item">
            <img src="${s}" alt="${r}" />
            <div class="info">
                <p><strong>Likes:</strong> <br> ${i}</p>
                <p><strong>Views:</strong> <br> ${l}</p>
                <p><strong>Comments:</strong> <br> ${u}</p>
                <p><strong>Downloads:</strong> <br> ${d}</p>
            </div>
        </a>
    `).join("");n.insertAdjacentHTML("beforeend",t)}function y(){document.querySelector(".loader").classList.add("visible")}function a(){document.querySelector(".loader").classList.remove("visible")}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector("#search-button"),n=document.querySelector("#search-input");if(!o||!n){console.error("Elements not found");return}let t=new g(".gallery a");o.addEventListener("click",function(){const s=n.value.trim();if(s===""){c.warning({title:"Warning",message:"Please enter a search query."});return}const e=document.querySelector(".gallery");e.innerHTML="",y(),h(s).then(r=>{a(),p(r),t.refresh()}).catch(r=>{a(),c.error({title:"Error",message:r.message})})})});
//# sourceMappingURL=index.js.map
